# Default values for nutanix-cloud-provider.
# This is a YAML-formatted file.

# Nutanix Prism Central
#

# Nutanix Prism Central settings
#
# Allow dynamic retrieval of nodes info
# Read-only RBAC is enough

# if set to true a new config will be created if not configName will be used
createConfig: true
configName: nutanix-config

prismCentralEndPoint: 10.0.0.1
prismCentralPort: 9440
prismCentralInsecure: false

# if set to true a new secret will not be created if not secretname will be used
createSecret: true
secretName: nutanix-creds

username: ccm
password: nutanix/4u

# Nutanix Cloud Provider Config
#

topologyCategories:
  region: region
  zone: zone

# Nutanix Cloud Provider Controller Settings
#

replicas: 1

image:
  repository: ghcr.io/nutanix-cloud-native/cloud-provider-nutanix/controller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

podAnnotations: {}

resources:
  requests:
    cpu: 100m
    memory: 50Mi

nodeSelector:
  node-role.kubernetes.io/control-plane: ""

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 120
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 120
  - effect: NoSchedule
    key: node.cloudprovider.kubernetes.io/uninitialized
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
    operator: Exists

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchLabels:
            k8s-app: nutanix-cloud-controller-manager
