apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ndb-operator-leader-election-rolebinding
  namespace: ndb-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ndb-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: ndb-operator-controller-manager
  namespace: ndb-operator-system
